### ISSUE TITLE
Fails during dkms install on Kernel 6.8.1

### ISSUE THREAD

**Issue by arillat** [radxa-pkg/8852be-dkms#2]
I think this can  help:

/var/lib/dkms/8852be/1.15.10.0.5.0.3/build/os_dep/linux/pci_intf.c:514:31: error: implicit declaration of function »pci_set_consistent_dma_mask« [-Werror=implicit-function-declaration]
  514 |                         err = pci_set_consistent_dma_mask(pdev, DMA_BIT_MASK(32));

**Comment by RadxaYuntian** [comment]
We currently only provide support for our own products. You might want to check this repo instead: https://github.com/lwfinger/rtw8852be
